name: Window 10
on: [push, workflow_dispatch]
jobs:
build:
runs-on: windows-latest
timeout-minutes: 9999
steps:
name: Download
run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFi
name:
Extract
Expand-Archive ngrok.zip
run:
Auth
name:
run: \ngrok\ngrok.exe authtoken $Env:NGROK AUTH TOKEN
env:
NGROK AUTH TOKEN: $(( secrets.NGROK AUTH TOKEN ))
name:
Enable TS
run: Set-ItemProperty Path "HKLM\System\CurrentControlSet\Control\Terminal Server-name "fDenyT
run: Enable-NetFirewallRule DisplayGroup "Remote Desktop"
run
: Set-ItemProperty Path "HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\R
run
: Set-Localuser Name "runneradein" -Password (Convert.To-SecureString AsPlainText "@cyb3rking
name:
Create Tunnel
in:Angrok\ngrok.exe tcp 3389
